import { Raleway } from 'next/font/google';

import type { Metadata } from 'next';
import './globals.css';

const raleway = Raleway({
  variable: '--font-raleway',
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'My Portfolio',
  description: 'Generated by create next app',
};

function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable} antialiased text-base text-gray-800`}
      >
        {children}
      </body>
    </html>
  );
}

export default RootLayout;
