import { Raleway } from 'next/font/google';

import type { Metadata } from 'next';

import './globals.css';
import { Footer } from './Footer';
import { Header } from './Header';

const raleway = Raleway({
  variable: '--font-raleway',
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'My Portfolio',
  description: 'Generated by create next app',
};

function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html data-theme="light" lang="pt">
      <body
        className={`${raleway.variable} antialiased text-base bg-background text-foreground`}
      >
        <Header />

        <section className="flex flex-col gap-4 px-4 md:px-8 xl:px-16 py-4">
          {children}
        </section>

        <Footer />
      </body>
    </html>
  );
}

export default RootLayout;
